// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcyRUpjeQ6Agbg-Qx5rzMpbyXGOHwhdYE',
    appId: '1:627061239274:web:b6557cad179a3754c4d693',
    messagingSenderId: '627061239274',
    projectId: 'cfcapp-57ff8',
    authDomain: 'cfcapp-57ff8.firebaseapp.com',
    databaseURL: 'https://cfcapp-57ff8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cfcapp-57ff8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4DHLsUh6JS2QsNdmctE9Bp1SFy0ye81Y',
    appId: '1:627061239274:android:556d83f240945274c4d693',
    messagingSenderId: '627061239274',
    projectId: 'cfcapp-57ff8',
    databaseURL: 'https://cfcapp-57ff8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cfcapp-57ff8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmsg3FfuDPubTgcqtRTZY8CO_5QV6xDsE',
    appId: '1:627061239274:ios:5930511cb44d5ebcc4d693',
    messagingSenderId: '627061239274',
    projectId: 'cfcapp-57ff8',
    databaseURL: 'https://cfcapp-57ff8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cfcapp-57ff8.appspot.com',
    androidClientId: '627061239274-uobu44elu7kpebbrvtaqh76l74in86qb.apps.googleusercontent.com',
    iosClientId: '627061239274-pno4bvulikaqtkjhfiaqdeabr7miirr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cfcapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmsg3FfuDPubTgcqtRTZY8CO_5QV6xDsE',
    appId: '1:627061239274:ios:5930511cb44d5ebcc4d693',
    messagingSenderId: '627061239274',
    projectId: 'cfcapp-57ff8',
    databaseURL: 'https://cfcapp-57ff8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cfcapp-57ff8.appspot.com',
    androidClientId: '627061239274-uobu44elu7kpebbrvtaqh76l74in86qb.apps.googleusercontent.com',
    iosClientId: '627061239274-pno4bvulikaqtkjhfiaqdeabr7miirr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cfcapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcyRUpjeQ6Agbg-Qx5rzMpbyXGOHwhdYE',
    appId: '1:627061239274:web:1c7ad67dfbb1074bc4d693',
    messagingSenderId: '627061239274',
    projectId: 'cfcapp-57ff8',
    authDomain: 'cfcapp-57ff8.firebaseapp.com',
    databaseURL: 'https://cfcapp-57ff8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cfcapp-57ff8.appspot.com',
  );
}
